server:
  port: 8080
spring:
  mvc: 
    view: 
      suffix: .html
  cache:
    type: redis
  session:
    store-type: redis
    redis:
      namespace: demian::session
  redis:
    host: localhost
#    password: 
    port: 6379
    
    