server:
  port: 8081
spring:
  mvc: 
    view: 
      suffix: .html
  security:
    user:
      password: 123
  cache:
    type: redis
  session:
    timeout: 10
    store-type: redis
    redis:
      namespace: redisTest::session
  redis:
    host: localhost
#    password: 
    port: 6379