server:
  port: 8084
  ssl:
    enabled: true
    protocol: TLS
    enabled-protocols:
      - TLSv1.2
      - TLSv1.3
    key-alias: tlstest
    key-password: dbghtmxm1!
    key-store: tlstest.pkcs12
    key-store-password: dbghtmxm1!
    trust-store: tlstesttrust.pkcs12
    trust-store-password: dbghtmxm1!
