server:
  port: 8080
spring:
  datasource:
    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://mysql:3306/k8s?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
#      username: root
#      password: dbghtmxm1
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
devtools:
  livereload:
    enabled: true