server:
  port: 8080
spring:
  datasource:
    hikari:
      primary:
#        jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/Factory_dongjin
        jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/Factory_moncat
        username: root
        password: dbghtmxm1!
      secondary:
        jdbc-url: jdbc:log4jdbc:mariadb://114.108.185.227:23306/sample
        username: root
        password: dbghtmxm1!
      third:
        jdbc-url: jdbc:log4jdbc:postgresql://114.108.185.227:5432/postgres
        username: postgres
        password: dbghtmxm1!
  influxdb:
    url: http://114.108.185.227:8086
    database: mybucket
    retention-policy: autogen
    username: sczedge
    password: dbghtmxm1!