server:
  port: 8080
spring:
  #Mariadb
  datasource:
    hikari:
      #jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/batch?characterEncoding=UTF-8&serverTimezone=UTC
      jdbc-url: jdbc:mariadb://localhost:3306/batch?characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: dbghtmxm1!
  mvc:
    view:
      suffix: .html